theme: jekyll-theme-midnight
title: Campagne di Fillo
sass:
  sass_dir: _sass
  style: compressed
repository: filloax/filloax.github.io
exclude:
  - "node_modules"
  - "package.json"
  - "Gruntfile.coffee"
  - "test_local.bat"
  - ".github"
collections:
  - star
  - xho
date_locale: it
